### ISSUE TITLE
AudioContext error in Chrome

### ISSUE THREAD

**Issue by speps** [martme/webaudio-modem#8]
> The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page.

I think you need to create the AudioContext when the encode button is clicked.

**Comment by exikyut** [comment]
I found the encoder randomly decided to get jammed in this mode (Chrome on Linux) after successfully working. Resetting the page permissions, going back to the decoder, accepting the microphone prompt, then going back to the encoder, seemed to fix it, although I'm probably just coincidentally unblocking whatever the real issue is by doing all that.

Chances are you probably need to put the AudioContext initialization code in an onclick callback. >.>

<sub>Edit: The >.> was me eyerolling at the understandable-but-sad status quo requiring these kinds of UI concessions, to be clear (and I'm surprised browser enforcement seems to be so inconsistent).</sub>

**Comment by daveloyall** [comment]
I'm using Firefox 102.0a1 (2022-05-25) (64-bit).

I get these messages in my console immediately after a ctrl+F5 reload.  I'm loading `encoder.html`.

> An AudioContext was prevented from starting automatically. It must be created or resumed after a user gesture on the page.

The page I loaded was modified in ... oh, 2018!  The audio api might have changed in the meantime. :)

I get the same message once on line 33 (`audioContext = new AudioContext();`) and eight times on line 43 (`oscillator.start();`).

I hope this helps.

**Comment by capnmidnight** [comment]
Here are some details on the exact issue: https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Best_practices#autoplay_policy

Note that a "user gesture" can be literally any click (or change, contextmenu, dblclick, mouseup, pointerup, reset, submit, or touchend event) on anything, including the page background itself, *including* the button on the previous page used to navigate to this page. But then, once you're on the page, refreshing it is not a *click inside of the document*, it's either a click outside of the document or a keypress.

You could just chuck a call `await oscillators[0].context.resume()` into the top of your `encode` function and it will always work.

**Comment by martme** [comment]
Thank you for reporting!

As has been noted, nothing has happened here for a couple of years, so browsers have changed since then. I hope you're happy with this very low effort workaround.
